import { StyleSheet } from "react-native";

export const homeStyles = StyleSheet.create({
  safeArea: {
    marginBottom: 20,
    backgroundColor: "#e7ecec",
    borderBottomColor: "#008080",
  },
  header: {
    paddingTop: 5,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 20,
  },
  gradientBox: {
    marginHorizontal: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
  },
  iconGrid: {
    // service icons container
    flexDirection: "column",
    alignContent: "center",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  iconBackground: {
    // service icon background
    backgroundColor: "#cceded",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 0.5,
    borderColor: "#b2d7d7",
    width: 70,
    height: 70,
    borderRadius: 35,
  },
  icons: {
    // service icon
    width: 70,
    height: 70,
    tintColor: "#008080",
  },
  iconText: {
    // service icon text
    color: "gray",
    fontSize: 16,
    marginTop: 5,
    textAlign: "center",
    marginHorizontal: 16,
    flexDirection: "row",
  },
  serviceBorder: { // most popular services border
    borderWidth: 1,
    borderColor: "#008080",
    borderRadius: 20,
    paddingLeft: 20,
    paddingRight: 20,
    padding: 10,
  },
  calendar: {
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    marginTop: 30,
  },
  calendarWrap: {
    width: 350,
    height: 370,
    borderRadius: 15,
    elevation: 5,
  },
  bookings: {
    backgroundColor: "#cceded",
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#b2d7d7",
    padding: 18,
    marginVertical: 10,
    marginHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  profile: {
    marginTop: 10,
    marginHorizontal: 30,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  border: { //services background
    backgroundColor: "#cceded",
    marginHorizontal: 20,
    marginTop: 12,
    borderRadius: 15,
    padding: 10,
    alignContent: "center",
    flexDirection: "column",
    borderWidth: 0.5,
    borderColor: "#b2d7d7",
  },
  borderTitle: { //services title
    paddingTop: 10,
    paddingBottom: 5,
    fontSize: 20,
    fontWeight: "500",
    marginHorizontal: 18,
  },
  borderDesc: { //services description
    fontSize: 13,
    color: "gray",
    lineHeight: 16,
    marginHorizontal: 18,
    marginBottom: 10,
  },
  marginEmergencyFix: { // Emergency Fix outside button
    alignContent: "center",
    justifyContent: "space-around",
    flexDirection: "row",
    marginHorizontal: 50,
    marginBottom: 15,
    marginTop: 10,
},
  emergencyFix: { // Emergency Fix button
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#008080",
    borderRadius: 15,
    paddingVertical: 20,
    paddingHorizontal: 25,
  },
  emergencyFixText: {
    fontSize: 20,
    fontWeight: "600",
    color: "white",
    marginLeft: 8,
  },
  findProvidersbtn:{
    fontSize: 16,
    fontWeight: "600",
    backgroundColor: "#008080",
    borderRadius: 8,
    color: "white",
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
   service_container: { 
    backgroundColor: "#008080",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignSelf: "flex-end",
  },
  service_text: { 
    fontSize: 16,
    fontWeight: "600",
    color: "white",
  },
  serviceproviderContainer: { // service provider container and background
    marginHorizontal: 20,
    marginTop: 15,
    flexDirection: "row",
    alignItems: "center",
    borderColor: "#b2d7d7",
    borderWidth: 0.5,
    backgroundColor: "#cceded", 
    borderRadius: 15,
    padding: 16,
   },
  providerText: { // type of service provider text
    color: "#008080",
    fontWeight: "bold",
    fontSize: 20,
  },
  providerTextContainer: {
    padding: 16,
    backgroundColor: "#fff",
  },
});

export default homeStyles;
